/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#fafafa",
        "on-error-container": "#fca5a5",
        "primary-container": "#7c3aed",
        "surface-container-low": "#0f0f12",
        "tertiary-fixed-dim": "#6ee7b7",
        "inverse-surface": "#fafafa",
        "secondary-container": "#27272a",
        "on-secondary-fixed": "#18181b",
        "on-primary-fixed": "#2e1065",
        "surface": "#0c0c0f",
        "surface-variant": "#18181b",
        "on-secondary-fixed-variant": "#3f3f46",
        "primary-fixed": "#ede9fe",
        "surface-dim": "#0c0c0f",
        "on-surface-variant": "#a1a1aa",
        "outline-variant": "#27272a",
        "on-primary-fixed-variant": "#5b21b6",
        "surface-container-lowest": "#09090b",
        "on-tertiary": "#001a12",
        "on-primary-container": "#ede9fe",
        "on-surface": "#fafafa",
        "on-primary": "#0a0012",
        "surface-tint": "#a78bfa",
        "inverse-primary": "#5b21b6",
        "error-container": "#3b1111",
        "on-secondary-container": "#a1a1aa",
        "outline": "#52525b",
        "surface-container-highest": "#1e1e22",
        "tertiary-fixed": "#bbf7d0",
        "surface-container-high": "#18181b",
        "secondary-fixed-dim": "#71717a",
        "error": "#ef4444",
        "secondary": "#71717a",
        "primary-fixed-dim": "#c4b5fd",
        "on-tertiary-container": "#bbf7d0",
        "on-secondary": "#09090b",
        "primary": "#a78bfa",
        "on-tertiary-fixed": "#003318",
        "tertiary": "#34d399",
        "surface-container": "#121215",
        "surface-bright": "#18181b",
        "inverse-on-surface": "#09090b",
        "on-tertiary-fixed-variant": "#047857",
        "on-error": "#1a0000",
        "secondary-fixed": "#a1a1aa",
        "tertiary-container": "#065f46",
        "background": "#09090b"
      },
      fontFamily: {
        "headline": ["Geist", "sans-serif"],
        "display": ["Geist", "sans-serif"],
        "body": ["Geist", "sans-serif"],
        "label": ["Geist", "sans-serif"]
      }
    },
  },
  plugins: [],
}
